project:
  type: website
  output-dir: docs

website:
  title: "The Developers Guide to GenAI"
  site-url: "https://baukebrenninkmeijer.github.io/developers-guide-to-genai"
  repo-url: "https://github.com/baukebrenninkmeijer/developers-guide-to-genai"

format:
  revealjs:
    slide-level: 2

react:
  components: _components
  resources: _components 